name: Run WebGoat with Contrast

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  run-webgoat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin

    - name: Download Contrast Agent
      run: wget -q -O contrast.jar https://download.java.contrastsecurity.com/latest

    - name: Set up Contrast environment variables
      run: |
        echo "CONTRAST__API__URL=${{ secrets.CONTRAST_API_URL }}" >> $GITHUB_ENV
        echo "CONTRAST__API__API_KEY=${{ secrets.CONTRAST_API_KEY }}" >> $GITHUB_ENV
        echo "CONTRAST__API__SERVICE_KEY=${{ secrets.CONTRAST_API_SERVICE_KEY }}" >> $GITHUB_ENV
        echo "CONTRAST__API__USER_NAME=${{ secrets.CONTRAST_API_USERNAME }}" >> $GITHUB_ENV
        echo "CONTRAST__API__ORG_ID=${{ secrets.CONTRAST_API_ORG_ID }}" >> $GITHUB_ENV
        echo "CONTRAST__API__APP_ID=${{ secrets.CONTRAST_API_APP_ID }}" >> $GITHUB_ENV

    - name: Run WebGoat
      run: |
        wget -q -O webgoat.jar https://github.com/WebGoat/WebGoat/releases/download/v2023.8/webgoat-2023.8.jar
        nohup java -Dcontrast.agent.logger.level=DEBUG -Dcontrast.agent.logger.stdout=true -Dcontrast.assess.max_context_source_events=50000 -javaagent:contrast.jar -Dcontrast.application_name=WebGoat -Dcontrast.application.session_metadata="branchName=${{ github.ref }},commitHash=${{ github.sha }},repository=${{ github.repository }}" -jar webgoat.jar &


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Wait for startup
      run: sleep 15 # Wait for WebGoat to start
    
    - name: Run script
      run: python exercise_sqli_5a.py

    - name: Wait for findings to be reported
      run: sleep 15

    - name: Pull Contrast findings
      run: |
        curl -vv -o findings.zip -H "Accept: application/x-zip-compressed" -H "Authorization: ${{secrets.CONTRAST_API_TOKEN}}" -H "API-Key: ${{secrets.CONTRAST_API_KEY}}" -H "Content-Type: application/json" -X POST ${{ secrets.CONTRAST_API_URL }}/api/ng/${{ secrets.CONTRAST_API_ORG_ID }}/traces/${{ secrets.CONTRAST_API_APP_ID }}/export/xml/all
        unzip findings.zip
        mv vulnerabilities*.xml findings.xml

    - name: Fix Contrast Findings with Pixeebot
      uses: pixee/upload-tool-results-action@v1.1.0
      with:
        tool: contrast
        file: findings.xml
