name: Run WebGoat with Contrast

on: [push]

jobs:
  run-webgoat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin

    - name: Download Contrast Agent
      run: wget -q -O contrast.jar https://download.java.contrastsecurity.com/latest

    - name: Set up Contrast environment variables
      run: |
        echo "CONTRAST__API__URL=${{ secrets.CONTRAST_API_URL }}" >> $GITHUB_ENV
        echo "CONTRAST__API__API_KEY==${{ secrets.CONTRAST_API_KEY }}" >> $GITHUB_ENV
        echo "CONTRAST__API__SERVICE_KEY==${{ secrets.CONTRAST_API_SERVICE_KEY }}" >> $GITHUB_ENV
        echo "CONTRAST__API__USER_NAME==${{ secrets.CONTRAST_API_USERNAME }}" >> $GITHUB_ENV

    - name: Run WebGoat
      run: |
        wget -q -O webgoat.jar https://github.com/WebGoat/WebGoat/releases/download/v2023.8/webgoat-2023.8.jar
        nohup java -javaagent:contrast.jar -Dcontrast.application_name=WebGoat -Dcontrast.application.session_metadata="branchName=${{ github.ref }},commitHash=${{ github.sha }},repository=${{ github.repository }}" -jar webgoat.jar &


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Wait for startup
      run: sleep 15 # Wait for WebGoat to start
    
    - name: Run script
      run: python exercise_sqli_5a.py
