name: HOTSPOTS ISSUES
on:
  check_run:
    types: [completed]

permissions:
  id-token: write

jobs:
  share:
    name: EL HOTSPOT
    runs-on: ubuntu-latest
    if: ${{ github.event.check_run.name == 'SonarCloud Code Analysis' }}
    steps:
      - uses: pixee/upload-tool-results-action@e3ac893c765a9ab8ed5674fbee5fc9c85ca1c53a
        with:
          tool: sonar
          sonar-token: ${{ secrets.SONAR_TOKEN }}
