name: HOTSPOTS ISSUES
on:
  check_run:
    types: [completed]

permissions:
  id-token: write

jobs:
  share:
    name: EL HOTSPOT
    runs-on: ubuntu-latest
    if: ${{ github.event.check_run.name == 'SonarCloud Code Analysis' }}
    steps:
      - uses: pixee/upload-tool-results-action@b1f48a7bcbd1077c5bbcfc17540fd79a3e82f10a
        with:
          tool: sonar
          sonar-token: ${{ secrets.SONAR_TOKEN }}
