name: HOTSPOTS ISSUES
on:
  check_run:
    types: [completed]

permissions:
  id-token: write

jobs:
  share:
    name: EL HOTSPOT
    runs-on: ubuntu-latest
    if: ${{ github.event.check_run.name == 'SonarCloud Code Analysis' }}
    steps:
      - uses: pixee/upload-tool-results-action@2e0d75df6fe9c22ce8982e34f56b60f8996af877
        with:
          tool: sonar
          sonar-token: ${{ secrets.SONAR_TOKEN }}
